### PR TITLE
[#68] Accommodate changes in error handling in Hybrid

### LINKED ISSUE #68: Accommodate changes in error handling
The class `Apigee\Edge\Exception\ApiResponseException` needs to be updated to handle changes in error response from Hybrid: 
```
{
  "error": {
      "code": 409,
      "message": "...",
      "status": "ABORTED",
      "details": [...]
  }
}

```

### PR DESCRIPTION
**Pull request by arlina-espinoza**
Closes #68 . Current Edge errors are returned as:
```
{
  "code": "...",
  "message": "..",
  "contexts": []
}
```
This PR adds support for Hybrid errors, which are returned in the format:
```
{
  "error": {
    "code": 403,
    "message": "unable to retrieve project information",
    "status": "PERMISSION_DENIED"
  }
}
```

### CODE REVIEW

**Comment by minnur** [comment]
Looks good to me.

**Review by minnur — APPROVED** [review]
Looks good to me.

File: src/Exception/ApiResponseException.php [hunk 1]
```diff
@@ -119,11 +119,17 @@ private function parseErrorResponse(ResponseInterface $response): array
...
+                    elseif (isset($array['error']['code'])) {
+                        $error['code'] = $array['error']['code'];
+                    }
                     if (array_key_exists('message', $array)) {
                         // It could happen that the returned message by
                         // Apigee Edge is also an array.
                         $error['message'] = is_array($array['message']) ? json_encode($array['message']) : $array['message'];
                     }
+                    elseif (isset($array['error']['message'])) {
+                        $error['message'] = $array['error']['message'];
```
Comment (mxr576) [inline src/Exception/ApiResponseException.php:129]: The status information in the message looks also important. Should not it be concatenated with the message string if it is set in the API response, so when this exception gets logged, the log entry would contain all information?

> "status": "PERMISSION_DENIED"

Comment (arlina-espinoza) [reply src/Exception/ApiResponseException.php:129]: @mxr576: I've added the status message if available.
