### PR TITLE
Fix user profile update not working on Apigee X (PUT /developers)

### LINKED ISSUE #153: User update on Apigee X not working
Steps to reproduce:

Try to update First and Last Name on the user on Drupal portal

# Steps to reproduce

1. In the Admin bar, click on "People"
2. Click to edit a user
3. Change a field such as First name or Last Name
4. Click "Save"

**Expected:**
User is updated

**Actual:**
System throws an error in the errorlog. No error is shown on the screen.

```PUT /developers/22222222-8359-49a1-b49b-d5cf959e9d83 HTTP/1.1
>>>>>>>>
PUT /v1/organizations/***organization***/developers/22222222-8359-49a1-b49b-d5cf959e9d83 HTTP/1.1
Host: apigee.googleapis.com
Content-Length: 371
X-Apigee-Edge-Api-Client-Profiler: X-Apigee-Edge-Api-Client-Profiler
Content-Type: application/json
User-Agent: Apigee Edge DevPortal 8.x-1.22 (Apigee Edge PHP Client 2.0.7)
Accept: application/json; charset=utf-8

{"apps":["APIM_Security_Demo_App","apim_mint_demoapp_1","app2"],"attributes":[],"companies":[],"createdAt":1623806970000,"developerId":"22222222-8359-49a1-b49b-d5cf959e9d83","email":"abcd@example.com","firstName":"abcd","lastModifiedAt":1623806970000,"lastName":"abcd","organizationName":"abcd-org1","status":"active","userName":"abcd1"}
<<<<<<<<
HTTP/1.1 400 Bad Request
Vary: X-Origin, Referer, Origin,Accept-Encoding
Content-Type: application/json; charset=UTF-8
Date: Wed, 16 Jun 2021 22:48:12 GMT
Server: ESF
Cache-Control: private
X-XSS-Protection: 0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Accept-Ranges: none
Transfer-Encoding: chunked

{
    "error": {
        "code": 400,
        "message": "Developer update : resource name 22222222-8359-49a1-b49b-d5cf959e9d83 in the url doesnot match with the name abcd@example.com in the request payload",
        "status": "INVALID_ARGUMENT",
        "details": [
            {
                "@type": "type.googleapis.com\/google.rpc.PreconditionFailure",
                "violations": [
                    {
                        "type": "rest.interceptor.name_mismatch",
                        "subject": "[2002:a17:531:8141::]:4177:vobi17:9855:347726:3196811",
                        "description": "Developer update : resource name 22222222-8359-49a1-b49b-d5cf959e9d83 in the url doesnot match with the name abcd@example.com in the request payload"
                    }
                ]
            },
            {
                "@type": "type.googleapis.com\/google.rpc.RequestInfo",
                "requestId": "3243783479475234489"
            }
        ]
    }
}
Transfer statistics:

total_time: 0.918s
namelookup_time: 0s
connect_time: 0s
pretransfer_time: 0s
starttransfer_time: 0.917s
redirect_time: 0s
appconnect_time: 0s
```

### PR DESCRIPTION
**Pull request by shishir-intelli**
Closes  #153 

Fixed issue by providing the developer `email-ID` instead of the developer `UUID` before clients `EntityUpdateOperationControllerTrait` update function is called.  (`PUT /developers` call)
This works for both 4G/ 5G.

Note: Also for Apigee X and hybrid runtime versions 1.5.0 and 1.5.1, a call to change the developer's email address will not work.

### CODE REVIEW

File: src/Entity/Property/EmailPropertyAwareTrait.php [hunk 1]
```diff
@@ -24,18 +24,36 @@ trait EmailPropertyAwareTrait
...
         $this->email = $email;
+        if (null === $this->originalEmail) {
+            $this->originalEmail = $email;
+        }
+    }
+
+    /**
+     * The original email address of the developer used when updating user email address.
+     */
+    public function originalEmail(): ?string
```
Comment (giteshk) [inline src/Entity/Property/EmailPropertyAwareTrait.php]: Can this be a private methods?

File: src/Entity/Property/EmailPropertyAwareTrait.php [hunk 2]
```diff
@@ -24,18 +24,36 @@ trait EmailPropertyAwareTrait
     protected $email;
```
Comment (giteshk) [inline src/Entity/Property/EmailPropertyAwareTrait.php:24]: Is this trait used anywhere else?

File: src/Entity/Property/EmailPropertyAwareTrait.php (hunk 1 above)
Comment (shishir-intelli) [reply src/Entity/Property/EmailPropertyAwareTrait.php]: @giteshk  No, this cant be a private/protected method, this is called by `DeveloperController` class from Management API.
This method is only used when updating the user profile and specially when updating users email address.

File: src/Entity/Property/EmailPropertyAwareTrait.php (hunk 2 above)
Comment (shishir-intelli) [reply src/Entity/Property/EmailPropertyAwareTrait.php:24]: Yes, this is generic trait for setting/getting email address.

Comment (giteshk) [reply src/Entity/Property/EmailPropertyAwareTrait.php:24]: Does it need it's own trail is what I am thinking. OriginalEmailPropertyAwareTrait ?

so if someone wanted to use EmailPropertyAwareTrait (e.g. DeveloperApps) trait in the future they would get this property by default even if they didn't want it.

Comment (shishir-intelli) [reply src/Entity/Property/EmailPropertyAwareTrait.php:24]: @giteshk I removed it from `EmailPropertyAwareTrait` and implemented in `Developer` entity. [Here](https://github.com/apigee/apigee-client-php/pull/154/commits/7c7a4fe24cd89cdac34836ba97813c171584bb6c)
(It is a method just to save the Original email address so trait not required.)

Comment (giteshk) [reply src/Entity/Property/EmailPropertyAwareTrait.php:24]: This looks better 👍 

Thank you

**Review by giteshk — APPROVED** [review]
LGTM .. Pending travis-ci.com migration. Please verify on your travis-ci instance.

File: src/Api/Management/Controller/DeveloperController.php [hunk 3]
```diff
@@ -95,7 +96,28 @@ public function getEntities(
...
 
     /**
-     * @inheritdoc
+     * {@inheritdoc}
+     *
+     * We are enforcing email addresses over developer ids (UUIDs) when we are updating user profile.
+     *
+     * @psalm-suppress PossiblyNullArgument $entity->originalEmail() is not null here.
+     *
+     *  @see https://github.com/apigee/apigee-client-php/issues/153
```
Comment (mxr576) [inline src/Api/Management/Controller/DeveloperController.php]: Nitpick unnecessary space before `@see`

File: src/Api/Management/Controller/DeveloperController.php [hunk 4]
```diff
@@ -104,7 +126,7 @@ protected function getBaseEndpointUri(): UriInterface
     }
 
     /**
-     * @inheritdoc
+     * {@inheritdoc}
```
Comment (mxr576) [inline src/Api/Management/Controller/DeveloperController.php:129]: IIRC it was intentionally `@inheritdoc` instead of the inlined version of it. Besides, it is an unrelated change, so I would propose changing this in a separate CR.

File: src/Api/Management/Entity/Developer.php [hunk 5]
```diff
@@ -44,6 +44,13 @@ class Developer extends AppOwner implements DeveloperInterface
     /** @var string[] */
     protected $companies = [];
 
+    /**
+    * The original email address of the developer.
+    *
+    * @var string|null
+    */
+    protected $originalEmail;
```
Comment (mxr576) [inline src/Api/Management/Entity/Developer.php]: Since here a public getter for this property, this property should be `private`, because no subclass should modify this directly. The related business logic is managed by the `setEmail()` class and both child classes and external caller should only use that public interface.

File: src/Api/Management/Entity/Developer.php [hunk 6]
```diff
@@ -91,58 +98,79 @@ public function setCompanies(string ...$companies): void
...
+            $this->originalEmail = $email;
+        }
+    }
+
+    /**
+     * The original email address of the developer used when updating user email address.
+     *
+     * @see Apigee\Edge\Api\Management\Controller\DeveloperController
+     */
+    public function originalEmail(): ?string
```
Comment (mxr576) [inline src/Api/Management/Entity/Developer.php:174]: Is there a reason for not having "get" as prefix?

**Review by mxr576 — CHANGES_REQUESTED** [review]

File: src/Api/Management/Entity/Developer.php (hunk 6 above)
Comment (shishir-intelli) [reply src/Api/Management/Entity/Developer.php:174]: Yes, implementing it as `GET` causes "`Invalid JSON payload received . Unknown name \"originalEmail\" at 'developer': Cannot find field.`" error and update fails.

File: src/Api/Management/Controller/DeveloperController.php (hunk 3 above)
Comment (shishir-intelli) [reply src/Api/Management/Controller/DeveloperController.php]: @mxr576 Updated.
Thanks for noticing it.

File: src/Api/Management/Entity/Developer.php (hunk 5 above)
Comment (shishir-intelli) [reply src/Api/Management/Entity/Developer.php]: @mxr576 Fixed,
You are right, Thanks!

File: src/Api/Management/Controller/DeveloperController.php (hunk 4 above)
Comment (shishir-intelli) [reply src/Api/Management/Controller/DeveloperController.php:129]: https://github.com/apigee/apigee-client-php/issues/157

File: src/Api/Management/Entity/Developer.php (hunk 6 above)
Comment (mxr576) [reply src/Api/Management/Entity/Developer.php:174]: Okay, so this happens because the default serialization solution in the library assumes that every public getter has to be serialized and added to the request payload.
A proper solution would be convincing the serializer not to serialize the `getOriginalEmail()`. IIRC there are examples for entity-type specific serializers in the library.

The other way around is keeping this method, marking them as `@internal` (even if it is public) and explaining in a short comment why it is not "get...".

File: src/Api/Management/Controller/DeveloperController.php (hunk 4 above)
Comment (mxr576) [reply src/Api/Management/Controller/DeveloperController.php:129]: Thanks, so please roll back unrelated changes from this PR if possible.

Comment (shishir-intelli) [reply src/Api/Management/Controller/DeveloperController.php:129]: @mxr576 if we roll back this change the `php-cs-fixer` throws `phpdoc_tag_type` error, so I think we should let this change go with this PR and for rest `phpdoc_tag_type` issue we can do it in #157

image
