### PR TITLE
Fix for Team app credentials listings sorted in ascending order

### LINKED ISSUE #338: Team app credentials listings are not in sorting order on the team app page.
## Description
Team app credentials listings are not in sorting order on the team app page.

## Apigee Info
Apigee X

### PR DESCRIPTION
**Pull request by kedarkhaire**
Closes #338

### CODE REVIEW

File: src/Api/Management/Entity/App.php [hunk 1]
```diff
@@ -187,6 +187,9 @@ public function setCallbackUrl(string $callbackUrl): void
      */
     public function getCredentials(): array
     {
+        usort($this->credentials, function (AppCredentialInterface $a, AppCredentialInterface $b) {
```
Comment (mxr576) [inline src/Api/Management/Entity/App.php]:
```suggestion
        usort($this->credentials, static function (AppCredentialInterface $a, AppCredentialInterface $b) {
```

as a minor memory usage improvement

Comment (mxr576) [reply src/Api/Management/Entity/App.php]: Also, consider using arrow functions for typing less :)

**Review by shishir-intelli — APPROVED** [review]
LGTM
